// id : serviceLocationData.id,
// streetAddress : serviceLocationData.address.streetAddress,
// state : serviceLocationData.address.state,
// city : serviceLocationData.address.city,
// zip : serviceLocationData.address.zip,
// latitude : serviceLocationData.address.latitude,
// longitude : serviceLocationData.address.longitude,
// bodiesOfWaterId : serviceLocationData.bodiesOfWaterId,
// chemicalCost : serviceLocationData.chemicalCost,
// customerId : serviceLocationData.customerId,
// customerName : serviceLocationData.customerName,
// gateCode : serviceLocationData.gateCode,
// laborCost : serviceLocationData.laborCost, //Maybe Remove
// laborType : serviceLocationData.laborType,
// mainContactEmail : serviceLocationData.contact.email,
// mainContactId : serviceLocationData.contact.id,
// mainContactName : serviceLocationData.contact.name,
// mainContactNotes : serviceLocationData.contact.notes,
// mainContactPhoneNumber : serviceLocationData.contact.phoneNumber,
// nickName : serviceLocationData.nickName,
// preText : serviceLocationData.preText,
// rate : serviceLocationData.rate, //Maybe Remove
// rateType : serviceLocationData.rateType, //Maybe Remove
// verified : serviceLocationData.verified,